"""
AES-GCM decryption helper for the scrambled-key .ns engine bundles.

Per-consumer module embeds its own scrambled key (key pad/xor + aad pad/xor)
and calls `decrypt_blob`, which reconstructs the real key + AAD locally in
mutable bytearrays, runs AESGCM.decrypt, then zeroes the bytearrays before
returning the plaintext bytes.

The transient `bytes(key_ba)` copy handed to AESGCM is immutable and can't be
wiped in pure Python, so this is best-effort — but a memory scan won't find
a contiguous 32-byte key sitting on any instance for the process lifetime.

Scramble parts are generated by services/scramble_key.py.
"""

import gc
from pathlib import Path

from cryptography.hazmat.primitives.ciphers.aead import AESGCM


def xor_reconstruct(pad: bytes, xored: bytes) -> bytearray:
    """XOR two equal-length byte strings into a mutable bytearray so the
    caller can zero it after use. Returning bytes would make the secret
    immutable and un-wipeable."""
    if len(pad) != len(xored):
        raise ValueError("scrambled parts length mismatch")
    out = bytearray(len(pad))
    for i in range(len(pad)):
        out[i] = pad[i] ^ xored[i]
    return out


def zero(ba: bytearray) -> None:
    for i in range(len(ba)):
        ba[i] = 0


def decrypt_blob(enc_path: Path,
                 key_pad: bytes, key_xor: bytes,
                 aad_pad: bytes, aad_xor: bytes) -> bytes:
    """Read iv(12) || ct+tag AES-GCM blob and return plaintext. Key + AAD
    are reconstructed locally in bytearrays and zeroed before return."""
    with open(enc_path, "rb") as f:
        blob = f.read()
    if len(blob) < 12 + 16:
        raise ValueError(f"Encrypted blob too small: {enc_path}")
    iv, ct = blob[:12], blob[12:]

    key_ba = xor_reconstruct(key_pad, key_xor)
    aad_ba = xor_reconstruct(aad_pad, aad_xor)
    try:
        aesgcm = AESGCM(bytes(key_ba))
        plaintext = aesgcm.decrypt(iv, ct, bytes(aad_ba))
    finally:
        zero(key_ba)
        zero(aad_ba)
        del key_ba, aad_ba
        gc.collect()
    return plaintext
