CLASS_MAPPINGS = {
        
    "Directional_Signage": {
        # ===== BASE LABELS (NO CONDITION) =====
        "Directional_Structure": 0,
        "Gantry_Directional_Sign": 1,
        "Street_Sign": 2,
        "Pole_Directional_Sign": 3,
        "Traffic_Sign": 4,
        
        # ===== WITH CONDITIONS =====
        "Directional_Structure_AssetCondition_Good": 5,
        "Directional_Structure_AssetCondition_Damaged": 6,
        "Gantry_Directional_Sign_AssetCondition_Good": 7,
        "Gantry_Directional_Sign_AssetCondition_Damaged": 8,
        "Street_Sign_AssetCondition_Good": 9,
        "Street_Sign_AssetCondition_Damaged": 10,
        "Pole_Directional_Sign_AssetCondition_Good": 11,
        "Pole_Directional_Sign_AssetCondition_Damaged": 12,
        "Traffic_Sign_AssetCondition_Good": 13,
        "Traffic_Sign_AssetCondition_Damaged": 14,
        "Traffic_Sign_AssetCondition_Dirty": 15,
        "Traffic_Sign_AssetCondition_Overgrown": 16,
    },
    
    # ============================================================
    # 2. ITS (Intelligent Transportation Systems) - 70 Classes
    # ============================================================
    "ITS": {
        # ===== BASE LABELS (NO CONDITION) =====
        "AIR_QUALITY_MONITORING_SYSTEM_AQMS": 0,
        "CLOSED_CIRCUIT_TELEVISION_CCTV": 1,
        "DYNAMIC_MESSAGE_SIGN_DMS": 2,
        "EMERGENCY_PHONE": 3,
        "FIRE_EXTINGUISHER": 4,
        "ITS_ENCLOSURE": 5,
        "ITS_FEEDER_PILLAR": 6,
        "ITS_STRUCTURE": 7,
        "LANE_CONTROL_SIGNS_LCS": 8,
        "OVER_HEIGHT_VEHICLE_DETECTION_SYSTEM_OVDS": 9,
        "OVDS_SPEAKER": 10,
        "ROAD_WEATHER_INFORMATION_SYSTEM_RWIS": 11,
        "SMALL_DYNAMIC_MESSAGING_SIGN": 12,
        "TRAFFIC_SIGNAL": 13,
        "TRAFFIC_SIGNAL_FEEDER_PILLAR": 14,
        "TRAFFIC_SIGNAL_HEAD": 15,
        "TRAFFIC_SIGNAL_JUNCTION": 16,
        "VEHICLE_RESTRAINT_SYSTEM": 17,
        
        # ===== WITH CONDITIONS =====
        "AIR_QUALITY_MONITORING_SYSTEM_AQMS_AssetCondition_Good": 18,
        "AIR_QUALITY_MONITORING_SYSTEM_AQMS_AssetCondition_Damaged": 19,
        "DYNAMIC_MESSAGE_SIGN_DMS_AssetCondition_Good": 20,
        "DYNAMIC_MESSAGE_SIGN_DMS_AssetCondition_Damaged": 21,
        "DYNAMIC_MESSAGE_SIGN_DMS_AssetCondition_NoDisplay": 22,
        "EMERGENCY_PHONE_AssetCondition_Good": 23,
        "EMERGENCY_PHONE_AssetCondition_Damaged": 24,
        "FIRE_EXTINGUISHER_AssetCondition_Fine": 25,
        "FIRE_EXTINGUISHER_AssetCondition_Missing": 26,
        "ITS_ENCLOSURE_AssetCondition_Visible": 27,
        "ITS_FEEDER_PILLAR_AssetCondition_Good": 28,
        "ITS_FEEDER_PILLAR_AssetCondition_Damaged": 29,
        "ITS_STRUCTURE_AssetCondition_Good": 30,
        "ITS_STRUCTURE_AssetCondition_Damaged": 31,
        "LANE_CONTROL_SIGNS_LCS_AssetCondition_Good": 32,
        "LANE_CONTROL_SIGNS_LCS_AssetCondition_Damaged": 33,
        "LANE_CONTROL_SIGNS_LCS_AssetCondition_NoDisplay": 34,
        "OVER_HEIGHT_VEHICLE_DETECTION_SYSTEM_OVDS_AssetCondition_Good": 35,
        "OVER_HEIGHT_VEHICLE_DETECTION_SYSTEM_OVDS_AssetCondition_Damaged": 36,
        "OVDS_SPEAKER_AssetCondition_Good": 37,
        "OVDS_SPEAKER_AssetCondition_Damaged": 38,
        "SMALL_DYNAMIC_MESSAGING_SIGN_AssetCondition_Good": 39,
        "SMALL_DYNAMIC_MESSAGING_SIGN_AssetCondition_Damaged": 40,
        "SMALL_DYNAMIC_MESSAGING_SIGN_AssetCondition_Display": 41,
        "TRAFFIC_SIGNAL_AssetCondition_Good": 42,
        "TRAFFIC_SIGNAL_AssetCondition_Damaged": 43,
        "TRAFFIC_SIGNAL_FEEDER_PILLAR_AssetCondition_Good": 44,
        "TRAFFIC_SIGNAL_FEEDER_PILLAR_AssetCondition_Damaged": 45,
        "TRAFFIC_SIGNAL_HEAD_AssetCondition_Good": 46,
        "TRAFFIC_SIGNAL_HEAD_AssetCondition_Damaged": 47,
        "TRAFFIC_SIGNAL_JUNCTION_AssetCondition_Good": 48,
        "VEHICLE_RESTRAINT_SYSTEM_AssetCondition_Good": 49,
        "VEHICLE_RESTRAINT_SYSTEM_AssetCondition_Damaged": 50,
    },
    
    # ============================================================
    # 3. OIA (Other Infrastructure Assets) - 34 Classes
    # ============================================================
    "OIA": {
        # ===== BASE LABELS (NO CONDITION) =====
        "Animal_Fence": 0,
        "Animal_Grid": 1,
        "Crash_Cushion": 2,
        "Fence": 3,
        "Guardrail": 4,
        "Traffic_Bollard": 5,
        
        # ===== WITH CONDITIONS =====
        "Animal_Fence_AssetCondition_Good": 6,
        "Animal_Fence_AssetCondition_Damaged": 7,
        "Animal_Fence_AssetCondition_MissingPanel": 8,
        "Animal_Grid_AssetCondition_Good": 9,
        "Animal_Grid_AssetCondition_Damaged": 10,
        "Crash_Cushion_AssetCondition_Good": 11,
        "Crash_Cushion_AssetCondition_Damaged": 12,
        "Crash_Cushion_AssetCondition_Missing": 13,
        "Fence_AssetCondition_Good": 14,
        "Fence_AssetCondition_Damaged": 15,
        "Fence_AssetCondition_Missing": 16,
        "Guardrail_AssetCondition_Good": 17,
        "Guardrail_AssetCondition_Damaged": 18,
        "Traffic_Bollard_AssetCondition_Good": 19,
        "Traffic_Bollard_AssetCondition_Missing": 20,
        "Traffic_Bollard_AssetCondition_Broken": 21,
        "Traffic_Bollard_AssetCondition_Bent": 22,
    },
    
    # ============================================================
    # 4. PAVEMENT - 51 Classes (16 base + 35 with conditions)
    # ============================================================
    "Pavement": {
        # ===== BASE LABELS (NO CONDITION) =====
        "Kerb": 0,
        "Road_Marking_Line": 1,
        "Road_Marking_Point": 2,
        "Road_Marking_Polygon": 3,
        "Road_Studs": 4,
        "Rumble_Strip": 5,
        "Speed_Humps": 6,
        "Accessway": 7,
        "Carriageway": 8,
        "Central_Roundabout_Island": 9,
        "Footpath": 10,
        "Junction_Island": 11,
        "Median": 12,
        "Parking_Bay": 13,
        "Separator_Island": 14,
        "Shoulder": 15,
        
        # ===== WITH CONDITIONS =====
        "Kerb_AssetCondition_Good": 16,
        "Kerb_AssetCondition_Damaged": 17,
        "Road_Marking_Line_AssetCondition_Good": 18,
        "Road_Marking_Line_AssetCondition_Damaged": 19,
        "Road_Marking_Point_AssetCondition_Good": 20,
        "Road_Marking_Point_AssetCondition_Damaged": 21,
        "Road_Marking_Polygon_AssetCondition_Good": 22,
        "Road_Marking_Polygon_AssetCondition_Damaged": 23,
        "Road_Marking_Polygon_AssetCondition_FadedPaint": 24,
        "Road_Studs_AssetCondition_Good": 25,
        "Road_Studs_AssetCondition_Broken": 26,
        "Road_Studs_AssetCondition_Missing": 27,
        "Rumble_Strip_AssetCondition_Good": 28,
        "Rumble_Strip_AssetCondition_Damaged": 29,
        "Rumble_Strip_AssetCondition_PaintFaded": 30,
        "Speed_Humps_AssetCondition_Good": 31,
        "Speed_Humps_AssetCondition_Damaged": 32,
        "Accessway_AssetCondition_Good": 33,
        "Accessway_AssetCondition_Damaged": 34,
        "Carriageway_AssetCondition_Good": 35,
        "Carriageway_AssetCondition_Damaged": 36,
        "Central_Roundabout_Island_AssetCondition_Good": 37,
        "Central_Roundabout_Island_AssetCondition_Damaged": 38,
        "Footpath_AssetCondition_Good": 39,
        "Footpath_AssetCondition_Damaged": 40,
        "Junction_Island_AssetCondition_Good": 41,
        "Junction_Island_AssetCondition_Damaged": 42,
        "Median_AssetCondition_Good": 43,
        "Median_AssetCondition_Damaged": 44,
        "Parking_Bay_AssetCondition_Good": 45,
        "Parking_Bay_AssetCondition_Poor": 46,
        "Separator_Island_AssetCondition_Good": 47,
        "Separator_Island_AssetCondition_Damaged": 48,
        "Shoulder_AssetCondition_Good": 49,
        "Shoulder_AssetCondition_Damaged": 50,
    },
    
    # ============================================================
    # 5. ROADWAY LIGHTING - 16 Classes (8 base + 8 with conditions)
    # ============================================================
    "Roadway_Lighting_Asset_Detection": {
        # ===== BASE LABELS (NO CONDITION) =====
        "STREET_LIGHT_FEEDER_PILLAR": 0,
        "STREET_LIGHT": 1,
        "STREET_LIGHT_POLE": 2,
        "UNDERPASS_LUMINAIRE": 3,
        
        # ===== WITH CONDITIONS =====
        "STREET_LIGHT_FEEDER_PILLAR_AssetCondition_Good": 4,
        "STREET_LIGHT_FEEDER_PILLAR_AssetCondition_Damaged": 5,
        "STREET_LIGHT_AssetCondition_Good": 6,
        "STREET_LIGHT_AssetCondition_Damaged": 7,
        "STREET_LIGHT_POLE_AssetCondition_Good": 8,
        "STREET_LIGHT_POLE_AssetCondition_Damaged": 9,
        "UNDERPASS_LUMINAIRE_AssetCondition_Good": 10,
        "UNDERPASS_LUMINAIRE_AssetCondition_Damaged": 11,
    },
    
    # ============================================================
    # 6. STRUCTURES - 60 Classes (30 base + 30 with conditions)
    # ============================================================
    "Structures_Asset_Detection": {
        # ===== BASE LABELS (NO CONDITION) =====
        "Bridge": 0,
        "Cable_Bridge": 1,
        "Camel_Crossing": 2,
        "Culvert": 3,
        "Flyover": 4,
        "Footbridge": 5,
        "Monument": 6,
        "Overpass_OP_Only_Pedestrian": 7,
        "Overpass_OV": 8,
        "Pedestrian_Underpass": 9,
        "Retaining_Wall": 10,
        "Toll_Gate": 11,
        "Tunnel": 12,
        "Underpass": 13,
        "Viaduct": 14,
        
        # ===== WITH CONDITIONS =====
        "Bridge_AssetCondition_Good": 15,
        "Bridge_AssetCondition_Damaged": 16,
        "Cable_Bridge_AssetCondition_Good": 17,
        "Cable_Bridge_AssetCondition_Damaged": 18,
        "Camel_Crossing_AssetCondition_Good": 19,
        "Camel_Crossing_AssetCondition_Damaged": 20,
        "Culvert_AssetCondition_Good": 21,
        "Culvert_AssetCondition_Damaged": 22,
        "Flyover_AssetCondition_Good": 23,
        "Flyover_AssetCondition_Damaged": 24,
        "Footbridge_AssetCondition_Good": 25,
        "Footbridge_AssetCondition_Damaged": 26,
        "Monument_AssetCondition_Good": 27,
        "Monument_AssetCondition_Damaged": 28,
        "Overpass_OP_Only_Pedestrian_AssetCondition_Good": 29,
        "Overpass_OP_Only_Pedestrian_AssetCondition_Damaged": 30,
        "Overpass_OV_AssetCondition_Good": 31,
        "Overpass_OV_AssetCondition_Damaged": 32,
        "Pedestrian_Underpass_AssetCondition_Good": 33,
        "Pedestrian_Underpass_AssetCondition_Damaged": 34,
        "Retaining_Wall_AssetCondition_Good": 35,
        "Retaining_Wall_AssetCondition_Damaged": 36,
        "Toll_Gate_AssetCondition_Good": 37,
        "Toll_Gate_AssetCondition_Damaged": 38,
        "Tunnel_AssetCondition_Good": 39,
        "Tunnel_AssetCondition_Damaged": 40,
        "Underpass_AssetCondition_Good": 41,
        "Underpass_AssetCondition_Damaged": 42,
        "Viaduct_VerticalClearance_Good": 43,
        "Viaduct_VerticalClearance_Damaged": 44,
    },
    
    # ============================================================
    # 7. BEAUTIFICATION - 23 Classes (BASE ONLY - NO CONDITIONS)
    # ============================================================
    "Beautification": {
        "Artificial_Grass": 0,
        "Bench": 1,
        "Bike_Rack": 2,
        "Bin": 3,
        "Decorative_Fence": 4,
        "Fitness_Equipment": 5,
        "Flower_Bed": 6,
        "Fountain": 7,
        "Garden": 8,
        "Gravel_Area": 9,
        "Hedge": 10,
        "Hoarding": 11,
        "Interlock_Area": 12,
        "Jogger_Track": 13,
        "Kerbstone": 14,
        "Landscape_Light": 15,
        "Natural_Grass": 16,
        "Planter_Pot": 17,
        "Recessed_Light": 18,
        "Road_Batter": 19,
        "Sand_Area": 20,
        "Tree": 21,
        "Treeguard": 22,
    },
}